### ISSUE TITLE
 Server Error: No such file or directory: './data/phrase-node-dataset/infos/eval/info-eval.gz'

### ISSUE THREAD

**Issue by igaurab** [stanfordnlp/web-elements#6]
Hi I  tried to use the chrome extension, but the server reply's
`[Error] No such file or directory: './data/phrase-node-dataset/infos/eval/info-eval.gz'`

I have no folder named `eval` inside my `infos` directory. Is `eval` folder created in runtime(after training)?

**Comment by ppasupat** [comment]
Hi! Could you try manually creating a folder named `eval` inside `infos`?

Note: The demo server is pretty hacky: it writes the page info json to a file (`info-eval.gz`) so that the dataset reader code can be reused. Ideally, the info should have been passed to the model directly.

**Comment by igaurab** [comment]
Awesome, it worked.
