### ISSUE TITLE
Training existing model for new data

### ISSUE THREAD

**Issue by kartikeu** [stanfordnlp/web-elements#7]
Hi, how can I fit an existing model to new training data? 
At the moment, I have to run the whole training process from scratch on old data+ new data. Is there a way to load an existing model and train it only on the added new data? In other words, is there a way for an existing model to learn on the fly for new training data?
I went through the argument parser in main.py but could not find any arguments to handle this case.

**Comment by ppasupat** [comment]
In `main.py`, if the positional argument (`config_paths`) is just a single number, the model will be loaded from the checkpoint in the corresponding experiment directory (e.g., specifying `7` loads the model from `./data/experiments/7_somename`). Then training will resume from the loaded model.

So for fine-tuning the model in `./data/experiments/7_somename` on *new data*, modify the config in `./data/experiments/7_somename/config.txt` to point to the new data, and then run `./main.py 7`.
(One can also copy `7_somename` to `8_someothername` first to preserve the content in `7_somename`.)

**Comment by kartikeu** [comment]
Thank you for the reply, I tried it and I'm getting a 'dirty_repo' error. It is not able to match the commits of the training runs. I am not sure how to rectify this.
I have attached the output from the command `./main.py 7`


/home/kartikey/Downloads/phrasenode/phrasenode-master/env/local/lib/python2.7/site-packages/torch/nn/_reduction.py:43: UserWarning: size_average and reduce args will be deprecated, please use reduction='none' instead.
  warnings.warn(warning.format(ret))

Read 14 examples (2 web pages) from ./data/phrase-node-dataset/data/combined-v2-cleaned.train.jsonl
Read 4 examples (1 web pages) from ./data/phrase-node-dataset/data/combined-v2-cleaned.dev.jsonl
Read 4 examples (1 web pages) from ./data/phrase-node-dataset/data/combined-v2-cleaned.test.jsonl

Traceback (most recent call last):
  File "./main.py", line 47, in <module>
    run = runs[int(config_paths[0])]
  File "/home/kartikey/Downloads/phrasenode/phrasenode-master/gtd/ml/training_run.py", line 145, in __getitem__
    run.match_commit(self._src_dir)
  File "/home/kartikey/Downloads/phrasenode/phrasenode-master/gtd/ml/training_run.py", line 104, in match_commit
    if self.metadata['dirty_repo']:
  File "/home/kartikey/Downloads/phrasenode/phrasenode-master/gtd/log.py", line 91, in __getitem__
    raise KeyError(key)

**Comment by kartikeu** [comment]
An update: I was able to run it by specifying `check_commit` as `False` and by increasing the `max_control_steps` in `config.txt` from `30000` to `40000`. Is changing check_commit to False safe?

**Comment by ppasupat** [comment]
Oh, just change `check_commit` to False. It is used to ensure reproducibility, but for development the flag can be set to False.

**Comment by kartikeu** [comment]
Okay, thanks a lot :)
